version: '3'

services:
  api:
    build: .
    command: poetry run python -m app.api
    restart: always
    container_name: "barbershop-api"
    ports:
      - "7999:15400"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: "barbershop-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
    driver: local
