"""init

Revision ID: 06fdbd5cd86c
Revises: 8d346255664f
Create Date: 2024-11-10 11:01:08.498911

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06fdbd5cd86c"
down_revision = "8d346255664f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client", sa.Column("next_appointment_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "client",
        "appointment",
        ["next_appointment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "client", type_="foreignkey")
    op.drop_column("client", "next_appointment_id")
    # ### end Alembic commands ###
