"""init

Revision ID: 585454a2272e
Revises: cdb29cb814c3
Create Date: 2024-11-06 23:26:06.542054

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "585454a2272e"
down_revision = "cdb29cb814c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointment", "next_sms_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointment",
        sa.Column(
            "next_sms_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
