"""init

Revision ID: 9e387f5a67d1
Revises: 715ab24bfeec
Create Date: 2024-11-01 22:20:21.763495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e387f5a67d1'
down_revision = '715ab24bfeec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
