"""init

Revision ID: c22a0fd2bbb5
Revises: 3eb131e8e143
Create Date: 2024-11-18 00:03:26.263822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22a0fd2bbb5'
down_revision = '3eb131e8e143'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('message_template_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'message_template', ['message_template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'message_template_id')
    # ### end Alembic commands ###
