"""init

Revision ID: fa2ef87b87fd
Revises: 0c4a51ceb695
Create Date: 2024-11-10 11:13:19.596009

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa2ef87b87fd"
down_revision = "0c4a51ceb695"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_appointment",
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("appointment_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"], ["appointment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("client_next_appointment_id_fkey", "client", type_="foreignkey")
    op.create_foreign_key(
        None,
        "client",
        "appointment",
        ["next_appointment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "client", type_="foreignkey")
    op.create_foreign_key(
        "client_next_appointment_id_fkey",
        "client",
        "appointment",
        ["next_appointment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("client_appointment")
    # ### end Alembic commands ###
