"""init

Revision ID: fb472a69c9eb
Revises: fa2ef87b87fd
Create Date: 2024-11-10 11:17:56.204472

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb472a69c9eb"
down_revision = "fa2ef87b87fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
